// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action.proto

/*
Package action is a generated protocol buffer package.

It is generated from these files:
	action.proto

It has these top-level messages:
	AlertEvent
	ActionResult
*/
package action

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlertEvent struct {
	AlertName string `protobuf:"bytes,1,opt,name=alertName" json:"alertName,omitempty"`
}

func (m *AlertEvent) Reset()                    { *m = AlertEvent{} }
func (m *AlertEvent) String() string            { return proto.CompactTextString(m) }
func (*AlertEvent) ProtoMessage()               {}
func (*AlertEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AlertEvent) GetAlertName() string {
	if m != nil {
		return m.AlertName
	}
	return ""
}

type ActionResult struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ActionResult) Reset()                    { *m = ActionResult{} }
func (m *ActionResult) String() string            { return proto.CompactTextString(m) }
func (*ActionResult) ProtoMessage()               {}
func (*ActionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ActionResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AlertEvent)(nil), "action.AlertEvent")
	proto.RegisterType((*ActionResult)(nil), "action.ActionResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Action service

type ActionClient interface {
	HandleAlert(ctx context.Context, in *AlertEvent, opts ...grpc.CallOption) (*ActionResult, error)
}

type actionClient struct {
	cc *grpc.ClientConn
}

func NewActionClient(cc *grpc.ClientConn) ActionClient {
	return &actionClient{cc}
}

func (c *actionClient) HandleAlert(ctx context.Context, in *AlertEvent, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := grpc.Invoke(ctx, "/action.Action/HandleAlert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Action service

type ActionServer interface {
	HandleAlert(context.Context, *AlertEvent) (*ActionResult, error)
}

func RegisterActionServer(s *grpc.Server, srv ActionServer) {
	s.RegisterService(&_Action_serviceDesc, srv)
}

func _Action_HandleAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionServer).HandleAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/action.Action/HandleAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionServer).HandleAlert(ctx, req.(*AlertEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _Action_serviceDesc = grpc.ServiceDesc{
	ServiceName: "action.Action",
	HandlerType: (*ActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleAlert",
			Handler:    _Action_HandleAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "action.proto",
}

func init() { proto.RegisterFile("action.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xb4, 0xb8, 0xb8,
	0x1c, 0x73, 0x52, 0x8b, 0x4a, 0x5c, 0xcb, 0x52, 0xf3, 0x4a, 0x84, 0x64, 0xb8, 0x38, 0x13, 0x41,
	0x3c, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x92, 0x1a,
	0x17, 0x8f, 0x23, 0x58, 0x57, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x18, 0x17, 0x5b, 0x71,
	0x49, 0x62, 0x49, 0x69, 0x31, 0x54, 0x29, 0x94, 0x67, 0xe4, 0xcc, 0xc5, 0x06, 0x51, 0x27, 0x64,
	0xc9, 0xc5, 0xed, 0x91, 0x98, 0x97, 0x92, 0x93, 0x0a, 0xb6, 0x43, 0x48, 0x48, 0x0f, 0xea, 0x06,
	0x84, 0x95, 0x52, 0x22, 0x70, 0x31, 0x24, 0xa3, 0x95, 0x18, 0x9c, 0x8c, 0xb9, 0x94, 0x92, 0xf3,
	0x73, 0xf5, 0x92, 0x12, 0xf3, 0xaa, 0x12, 0x33, 0x93, 0x73, 0xf2, 0x4b, 0x53, 0xf4, 0x32, 0xf2,
	0x73, 0x72, 0xf2, 0xcb, 0x4b, 0x8a, 0x52, 0x53, 0x8b, 0xa1, 0x9a, 0x9c, 0xb8, 0x21, 0xba, 0x02,
	0x40, 0x7e, 0x0a, 0x60, 0x4c, 0x62, 0x03, 0x7b, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x44,
	0xcb, 0xdf, 0x7b, 0xec, 0x00, 0x00, 0x00,
}
